import { defineConfig } from "tsdown";

export default defineConfig({
  entry: ["./src/index.ts", "./src/runTestCli.ts", "./src/wgslTestMain.ts"],
  target: "node22",
  clean: true,
  dts: true,
  sourcemap: true,
  platform: "neutral",
  external: [
    "../lib/weslBundle.js",
    "fs",
    "module",
    "node:assert",
    "node:events",
    "node:fs",
    "node:fs/promises",
    "node:module",
    "node:path",
    "node:process",
    "node:stream",
    "node:string_decoder",
    "node:url",
    "node:util",
    "node:v8",
    "vitest",
    "vitest-image-snapshot",
    "wesl",
    "wesl-gpu",
    "wesl-tooling",
  ],
  logLevel: "warn",
});
