import { styleTags, tags as t } from "@lezer/highlight";

/** Syntax highlighting for WESL */
export const weslHighlighting = styleTags({
  Number: t.number,
  Boolean: t.bool,
  LineComment: t.lineComment,
  BlockComment: t.blockComment,
  Import: t.keyword,
  "import as": t.keyword,
  "FunctionDeclaration/Kw": t.controlKeyword,
  "IfStatement/Kw": t.controlKeyword,
  "SwitchStatement/Kw": t.controlKeyword,
  "SwitchClause/Kw": t.controlKeyword,
  "LoopStatement/Kw": t.controlKeyword,
  "LoopBlock/Kw": t.controlKeyword,
  "ForStatement/Kw": t.controlKeyword,
  "WhileStatement/Kw": t.controlKeyword,
  "Statement/Kw": t.controlKeyword,
  "GlobalVariableDeclaration/Kw": t.definitionKeyword,
  "GlobalValueDeclaration/Kw": t.definitionKeyword,
  "VarStatement/Kw": t.definitionKeyword,
  "StructDeclaration/Kw": t.definitionKeyword,
  "TypeAliasDeclaration/Kw": t.definitionKeyword,
  "DiagnosticDirective/Kw": t.keyword,
  "EnableDirective/Kw": t.keyword,
  "RequiresDirective/Kw": t.keyword,
  "ConstAssert/Kw": t.keyword,
  "TypeOrExpr/Kw": t.keyword,
  BuiltinType: t.keyword,
  BuiltinFn: t.keyword,
  Identifier: t.variableName,
  "Type/Identifier": t.typeName,
  "TypeOrExpr/Identifier": t.typeName,
  "FunctionDeclaration/Identifier": t.function(t.definition(t.variableName)),
  "StructDeclaration/Identifier": t.definition(t.typeName),
  "Param/Identifier": t.definition(t.variableName),
  "StructMember/Identifier": t.propertyName,
  "VarStatement/Identifier": t.definition(t.variableName),
  "GlobalVariableDeclaration/Identifier": t.definition(t.variableName),
  "GlobalValueDeclaration/Identifier": t.definition(t.variableName),
  "FunctionDeclaration/BuiltinFn": t.function(t.definition(t.variableName)),
  "StructDeclaration/BuiltinFn": t.definition(t.typeName),
  "Param/BuiltinFn": t.definition(t.variableName),
  "StructMember/BuiltinFn": t.propertyName,
  "VarStatement/BuiltinFn": t.definition(t.variableName),
  "GlobalVariableDeclaration/BuiltinFn": t.definition(t.variableName),
  "GlobalValueDeclaration/BuiltinFn": t.definition(t.variableName),
  "ImportPath/Identifier": t.namespace,
  "ImportItem/Identifier": t.namespace,
  "ImportPath/Kw": t.keyword,
  "PathBase/Identifier": t.namespace,
  "PathExpression/Identifier": t.function(t.variableName),
  "CallExpression/Identifier": t.typeName,
  "StandardAttribute/Identifier": t.keyword,
  '"=" "+=" "-=" "*=" "/=" "%=" "&=" "|=" "^=" "<<=" ">>="':
    t.definitionOperator,
  "++ --": t.updateOperator,
  "( )": t.paren,
  "[ ]": t.squareBracket,
  "{ }": t.brace,
  ". , ; : -> ::": t.punctuation,
  "< >": t.angleBracket,
});
