packages:
- 'packages/*'
- 'packages/test_pkg/*'
- 'packages/wesl-plugin/test/linkExtension'
- 'packages/wesl-plugin/test/linkExtensionNoToml'
- 'packages/wesl-plugin/test/staticExtension'
- 'examples/*'
