import type { RcFile } from "syncpack";
export default {
  sortFirst: [
    "name",
    "description",
    "version",
    "private",
    "author",
    "type",
    "bin",
    "files",
    "repository",
    "homepage",
    "scripts",
    "exports",
    "main",
    "module",
    "types",
    "dependencies",
    "devDependencies",
    "peerDependencies",
    "license",
    "keywords",
    "packageManager",
  ],
  versionGroups: [
    { label: "plugin is weird", packages: ["wesl-plugin"], isIgnored: true },
    {
      label: "Use workspace:^ for peer dependencies on local packages",
      dependencies: ["$LOCAL"],
      dependencyTypes: ["peer"],
      pinVersion: "workspace:^",
    },
    {
      label: "Use workspace:* for dev/prod dependencies on local packages",
      dependencies: ["$LOCAL"],
      dependencyTypes: ["dev", "prod"],
      pinVersion: "workspace:*",
    },
  ],
} satisfies RcFile;
