name: CI

on:
  push:
    branches: [tomain, lee/ci, stefnotch/ci]
  pull_request:
    branches: [main]

jobs:
  validate:
    strategy:
      matrix:
       os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run CI checks (macOS)
        if: matrix.os == 'macos-latest'
        run: pnpm ci:check

      - name: Run CI checks (Windows)
        if: matrix.os == 'windows-latest'
        run: pnpm ci:check-windows